# ============================================================
#                     VERSION CATALOG
#        Clean, cohesive, and modern Kotlin/Compose setup
# ============================================================

[versions]

# --- Core Toolchains (Upgraded to Modern Stack) ---
kotlin-ver = "2.4.0"             # was 2.3.20
agp = "9.5.0-alpha01"             # was 9.2.1 and earlier 8.8.0
jvm = "21"

android-compileSdk = "37"         # was 36 35 compileSd
android-minSdk = "24"
android-targetSdk = "36"         # was 36 35

lifecycle = "2.10.0"
ksp-ver = "2.4.0-1.0.26"          # was 2.3.8
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.6.1"
material = "1.10.0"
# --- Misc ---
kotlinxSerialization = "1.9.0"    # was 1.7.3
mockk-ver = "1.14.7"              # was 1.13.13
#jna-ver = "5.18.1"                # was 5.15.0
snakeyaml-ver = "2.5"             # was 2.3
dokka-ver = "2.2.0"               # was 2.1.0

[plugins]
# Kotlin
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-ver" }
#room = { id = "androidx.room", version.ref = "room-ver" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-ver" }
kotlinJvm           = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-ver" }

# Tooling
# ksp   = { id = "com.google.devtools.ksp", version.ref = "ksp-ver" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka-ver" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-ver" }

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

# --- Plugin Artifacts (Required for build-logic) ---
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-ver" }
kotlin-serialization-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin-ver" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp-ver" }
dokka-gradle-plugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka-ver" }